// AUTO-GENERATED by scripts/generate-filled-icons.mjs — do not edit.
import s0 from "./arrow-left.svg?raw";
import s1 from "./arrow-right.svg?raw";
import s2 from "./arrow-up-right.svg?raw";
import s3 from "./calendar.svg?raw";
import s4 from "./check.svg?raw";
import s5 from "./chevron-down.svg?raw";
import s6 from "./chevron-left.svg?raw";
import s7 from "./chevron-right.svg?raw";
import s8 from "./chevron-up.svg?raw";
import s9 from "./circle.svg?raw";
import s10 from "./copy.svg?raw";
import s11 from "./external-link.svg?raw";
import s12 from "./globe.svg?raw";
import s13 from "./grip-vertical.svg?raw";
import s14 from "./heart.svg?raw";
import s15 from "./info.svg?raw";
import s16 from "./mail.svg?raw";
import s17 from "./map.svg?raw";
import s18 from "./map-pin.svg?raw";
import s19 from "./menu.svg?raw";
import s20 from "./minus.svg?raw";
import s21 from "./more-horizontal.svg?raw";
import s22 from "./navigation.svg?raw";
import s23 from "./panel-left.svg?raw";
import s24 from "./phone.svg?raw";
import s25 from "./search.svg?raw";
import s26 from "./sprout.svg?raw";
import s27 from "./tag.svg?raw";
import s28 from "./users.svg?raw";
import s29 from "./x.svg?raw";

export interface FilledIcon { name: string; kebab: string; raw: string }
export const filledIcons: FilledIcon[] = [
  { name: "ArrowLeft", kebab: "arrow-left", raw: s0 },
  { name: "ArrowRight", kebab: "arrow-right", raw: s1 },
  { name: "ArrowUpRight", kebab: "arrow-up-right", raw: s2 },
  { name: "Calendar", kebab: "calendar", raw: s3 },
  { name: "Check", kebab: "check", raw: s4 },
  { name: "ChevronDown", kebab: "chevron-down", raw: s5 },
  { name: "ChevronLeft", kebab: "chevron-left", raw: s6 },
  { name: "ChevronRight", kebab: "chevron-right", raw: s7 },
  { name: "ChevronUp", kebab: "chevron-up", raw: s8 },
  { name: "Circle", kebab: "circle", raw: s9 },
  { name: "Copy", kebab: "copy", raw: s10 },
  { name: "ExternalLink", kebab: "external-link", raw: s11 },
  { name: "Globe", kebab: "globe", raw: s12 },
  { name: "GripVertical", kebab: "grip-vertical", raw: s13 },
  { name: "Heart", kebab: "heart", raw: s14 },
  { name: "Info", kebab: "info", raw: s15 },
  { name: "Mail", kebab: "mail", raw: s16 },
  { name: "Map", kebab: "map", raw: s17 },
  { name: "MapPin", kebab: "map-pin", raw: s18 },
  { name: "Menu", kebab: "menu", raw: s19 },
  { name: "Minus", kebab: "minus", raw: s20 },
  { name: "MoreHorizontal", kebab: "more-horizontal", raw: s21 },
  { name: "Navigation", kebab: "navigation", raw: s22 },
  { name: "PanelLeft", kebab: "panel-left", raw: s23 },
  { name: "Phone", kebab: "phone", raw: s24 },
  { name: "Search", kebab: "search", raw: s25 },
  { name: "Sprout", kebab: "sprout", raw: s26 },
  { name: "Tag", kebab: "tag", raw: s27 },
  { name: "Users", kebab: "users", raw: s28 },
  { name: "X", kebab: "x", raw: s29 }
];
