/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegionerRouteImport } from './routes/regioner'
import { Route as OmOssRouteImport } from './routes/om-oss'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as KategorierRouteImport } from './routes/kategorier'
import { Route as KartaRouteImport } from './routes/karta'
import { Route as GardsforsaljareRouteImport } from './routes/gardsforsaljare'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as BloggNyheterRouteImport } from './routes/blogg-nyheter'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegionerIndexRouteImport } from './routes/regioner.index'
import { Route as KategorierIndexRouteImport } from './routes/kategorier.index'
import { Route as GardsforsaljareIndexRouteImport } from './routes/gardsforsaljare.index'
import { Route as BloggNyheterIndexRouteImport } from './routes/blogg-nyheter.index'
import { Route as RegionerSlugRouteImport } from './routes/regioner.$slug'
import { Route as KategorierSlugRouteImport } from './routes/kategorier.$slug'
import { Route as GardsforsaljareSlugRouteImport } from './routes/gardsforsaljare.$slug'
import { Route as BloggNyheterSlugRouteImport } from './routes/blogg-nyheter.$slug'

const RegionerRoute = RegionerRouteImport.update({
  id: '/regioner',
  path: '/regioner',
  getParentRoute: () => rootRouteImport,
} as any)
const OmOssRoute = OmOssRouteImport.update({
  id: '/om-oss',
  path: '/om-oss',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const KategorierRoute = KategorierRouteImport.update({
  id: '/kategorier',
  path: '/kategorier',
  getParentRoute: () => rootRouteImport,
} as any)
const KartaRoute = KartaRouteImport.update({
  id: '/karta',
  path: '/karta',
  getParentRoute: () => rootRouteImport,
} as any)
const GardsforsaljareRoute = GardsforsaljareRouteImport.update({
  id: '/gardsforsaljare',
  path: '/gardsforsaljare',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const BloggNyheterRoute = BloggNyheterRouteImport.update({
  id: '/blogg-nyheter',
  path: '/blogg-nyheter',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionerIndexRoute = RegionerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RegionerRoute,
} as any)
const KategorierIndexRoute = KategorierIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KategorierRoute,
} as any)
const GardsforsaljareIndexRoute = GardsforsaljareIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GardsforsaljareRoute,
} as any)
const BloggNyheterIndexRoute = BloggNyheterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BloggNyheterRoute,
} as any)
const RegionerSlugRoute = RegionerSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => RegionerRoute,
} as any)
const KategorierSlugRoute = KategorierSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => KategorierRoute,
} as any)
const GardsforsaljareSlugRoute = GardsforsaljareSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GardsforsaljareRoute,
} as any)
const BloggNyheterSlugRoute = BloggNyheterSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BloggNyheterRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blogg-nyheter': typeof BloggNyheterRouteWithChildren
  '/design-system': typeof DesignSystemRoute
  '/faq': typeof FaqRoute
  '/gardsforsaljare': typeof GardsforsaljareRouteWithChildren
  '/karta': typeof KartaRoute
  '/kategorier': typeof KategorierRouteWithChildren
  '/kontakt': typeof KontaktRoute
  '/om-oss': typeof OmOssRoute
  '/regioner': typeof RegionerRouteWithChildren
  '/blogg-nyheter/$slug': typeof BloggNyheterSlugRoute
  '/gardsforsaljare/$slug': typeof GardsforsaljareSlugRoute
  '/kategorier/$slug': typeof KategorierSlugRoute
  '/regioner/$slug': typeof RegionerSlugRoute
  '/blogg-nyheter/': typeof BloggNyheterIndexRoute
  '/gardsforsaljare/': typeof GardsforsaljareIndexRoute
  '/kategorier/': typeof KategorierIndexRoute
  '/regioner/': typeof RegionerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/design-system': typeof DesignSystemRoute
  '/faq': typeof FaqRoute
  '/karta': typeof KartaRoute
  '/kontakt': typeof KontaktRoute
  '/om-oss': typeof OmOssRoute
  '/blogg-nyheter/$slug': typeof BloggNyheterSlugRoute
  '/gardsforsaljare/$slug': typeof GardsforsaljareSlugRoute
  '/kategorier/$slug': typeof KategorierSlugRoute
  '/regioner/$slug': typeof RegionerSlugRoute
  '/blogg-nyheter': typeof BloggNyheterIndexRoute
  '/gardsforsaljare': typeof GardsforsaljareIndexRoute
  '/kategorier': typeof KategorierIndexRoute
  '/regioner': typeof RegionerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blogg-nyheter': typeof BloggNyheterRouteWithChildren
  '/design-system': typeof DesignSystemRoute
  '/faq': typeof FaqRoute
  '/gardsforsaljare': typeof GardsforsaljareRouteWithChildren
  '/karta': typeof KartaRoute
  '/kategorier': typeof KategorierRouteWithChildren
  '/kontakt': typeof KontaktRoute
  '/om-oss': typeof OmOssRoute
  '/regioner': typeof RegionerRouteWithChildren
  '/blogg-nyheter/$slug': typeof BloggNyheterSlugRoute
  '/gardsforsaljare/$slug': typeof GardsforsaljareSlugRoute
  '/kategorier/$slug': typeof KategorierSlugRoute
  '/regioner/$slug': typeof RegionerSlugRoute
  '/blogg-nyheter/': typeof BloggNyheterIndexRoute
  '/gardsforsaljare/': typeof GardsforsaljareIndexRoute
  '/kategorier/': typeof KategorierIndexRoute
  '/regioner/': typeof RegionerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blogg-nyheter'
    | '/design-system'
    | '/faq'
    | '/gardsforsaljare'
    | '/karta'
    | '/kategorier'
    | '/kontakt'
    | '/om-oss'
    | '/regioner'
    | '/blogg-nyheter/$slug'
    | '/gardsforsaljare/$slug'
    | '/kategorier/$slug'
    | '/regioner/$slug'
    | '/blogg-nyheter/'
    | '/gardsforsaljare/'
    | '/kategorier/'
    | '/regioner/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/design-system'
    | '/faq'
    | '/karta'
    | '/kontakt'
    | '/om-oss'
    | '/blogg-nyheter/$slug'
    | '/gardsforsaljare/$slug'
    | '/kategorier/$slug'
    | '/regioner/$slug'
    | '/blogg-nyheter'
    | '/gardsforsaljare'
    | '/kategorier'
    | '/regioner'
  id:
    | '__root__'
    | '/'
    | '/blogg-nyheter'
    | '/design-system'
    | '/faq'
    | '/gardsforsaljare'
    | '/karta'
    | '/kategorier'
    | '/kontakt'
    | '/om-oss'
    | '/regioner'
    | '/blogg-nyheter/$slug'
    | '/gardsforsaljare/$slug'
    | '/kategorier/$slug'
    | '/regioner/$slug'
    | '/blogg-nyheter/'
    | '/gardsforsaljare/'
    | '/kategorier/'
    | '/regioner/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BloggNyheterRoute: typeof BloggNyheterRouteWithChildren
  DesignSystemRoute: typeof DesignSystemRoute
  FaqRoute: typeof FaqRoute
  GardsforsaljareRoute: typeof GardsforsaljareRouteWithChildren
  KartaRoute: typeof KartaRoute
  KategorierRoute: typeof KategorierRouteWithChildren
  KontaktRoute: typeof KontaktRoute
  OmOssRoute: typeof OmOssRoute
  RegionerRoute: typeof RegionerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/regioner': {
      id: '/regioner'
      path: '/regioner'
      fullPath: '/regioner'
      preLoaderRoute: typeof RegionerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/om-oss': {
      id: '/om-oss'
      path: '/om-oss'
      fullPath: '/om-oss'
      preLoaderRoute: typeof OmOssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kategorier': {
      id: '/kategorier'
      path: '/kategorier'
      fullPath: '/kategorier'
      preLoaderRoute: typeof KategorierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/karta': {
      id: '/karta'
      path: '/karta'
      fullPath: '/karta'
      preLoaderRoute: typeof KartaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gardsforsaljare': {
      id: '/gardsforsaljare'
      path: '/gardsforsaljare'
      fullPath: '/gardsforsaljare'
      preLoaderRoute: typeof GardsforsaljareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogg-nyheter': {
      id: '/blogg-nyheter'
      path: '/blogg-nyheter'
      fullPath: '/blogg-nyheter'
      preLoaderRoute: typeof BloggNyheterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regioner/': {
      id: '/regioner/'
      path: '/'
      fullPath: '/regioner/'
      preLoaderRoute: typeof RegionerIndexRouteImport
      parentRoute: typeof RegionerRoute
    }
    '/kategorier/': {
      id: '/kategorier/'
      path: '/'
      fullPath: '/kategorier/'
      preLoaderRoute: typeof KategorierIndexRouteImport
      parentRoute: typeof KategorierRoute
    }
    '/gardsforsaljare/': {
      id: '/gardsforsaljare/'
      path: '/'
      fullPath: '/gardsforsaljare/'
      preLoaderRoute: typeof GardsforsaljareIndexRouteImport
      parentRoute: typeof GardsforsaljareRoute
    }
    '/blogg-nyheter/': {
      id: '/blogg-nyheter/'
      path: '/'
      fullPath: '/blogg-nyheter/'
      preLoaderRoute: typeof BloggNyheterIndexRouteImport
      parentRoute: typeof BloggNyheterRoute
    }
    '/regioner/$slug': {
      id: '/regioner/$slug'
      path: '/$slug'
      fullPath: '/regioner/$slug'
      preLoaderRoute: typeof RegionerSlugRouteImport
      parentRoute: typeof RegionerRoute
    }
    '/kategorier/$slug': {
      id: '/kategorier/$slug'
      path: '/$slug'
      fullPath: '/kategorier/$slug'
      preLoaderRoute: typeof KategorierSlugRouteImport
      parentRoute: typeof KategorierRoute
    }
    '/gardsforsaljare/$slug': {
      id: '/gardsforsaljare/$slug'
      path: '/$slug'
      fullPath: '/gardsforsaljare/$slug'
      preLoaderRoute: typeof GardsforsaljareSlugRouteImport
      parentRoute: typeof GardsforsaljareRoute
    }
    '/blogg-nyheter/$slug': {
      id: '/blogg-nyheter/$slug'
      path: '/$slug'
      fullPath: '/blogg-nyheter/$slug'
      preLoaderRoute: typeof BloggNyheterSlugRouteImport
      parentRoute: typeof BloggNyheterRoute
    }
  }
}

interface BloggNyheterRouteChildren {
  BloggNyheterSlugRoute: typeof BloggNyheterSlugRoute
  BloggNyheterIndexRoute: typeof BloggNyheterIndexRoute
}

const BloggNyheterRouteChildren: BloggNyheterRouteChildren = {
  BloggNyheterSlugRoute: BloggNyheterSlugRoute,
  BloggNyheterIndexRoute: BloggNyheterIndexRoute,
}

const BloggNyheterRouteWithChildren = BloggNyheterRoute._addFileChildren(
  BloggNyheterRouteChildren,
)

interface GardsforsaljareRouteChildren {
  GardsforsaljareSlugRoute: typeof GardsforsaljareSlugRoute
  GardsforsaljareIndexRoute: typeof GardsforsaljareIndexRoute
}

const GardsforsaljareRouteChildren: GardsforsaljareRouteChildren = {
  GardsforsaljareSlugRoute: GardsforsaljareSlugRoute,
  GardsforsaljareIndexRoute: GardsforsaljareIndexRoute,
}

const GardsforsaljareRouteWithChildren = GardsforsaljareRoute._addFileChildren(
  GardsforsaljareRouteChildren,
)

interface KategorierRouteChildren {
  KategorierSlugRoute: typeof KategorierSlugRoute
  KategorierIndexRoute: typeof KategorierIndexRoute
}

const KategorierRouteChildren: KategorierRouteChildren = {
  KategorierSlugRoute: KategorierSlugRoute,
  KategorierIndexRoute: KategorierIndexRoute,
}

const KategorierRouteWithChildren = KategorierRoute._addFileChildren(
  KategorierRouteChildren,
)

interface RegionerRouteChildren {
  RegionerSlugRoute: typeof RegionerSlugRoute
  RegionerIndexRoute: typeof RegionerIndexRoute
}

const RegionerRouteChildren: RegionerRouteChildren = {
  RegionerSlugRoute: RegionerSlugRoute,
  RegionerIndexRoute: RegionerIndexRoute,
}

const RegionerRouteWithChildren = RegionerRoute._addFileChildren(
  RegionerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BloggNyheterRoute: BloggNyheterRouteWithChildren,
  DesignSystemRoute: DesignSystemRoute,
  FaqRoute: FaqRoute,
  GardsforsaljareRoute: GardsforsaljareRouteWithChildren,
  KartaRoute: KartaRoute,
  KategorierRoute: KategorierRouteWithChildren,
  KontaktRoute: KontaktRoute,
  OmOssRoute: OmOssRoute,
  RegionerRoute: RegionerRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
