/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegionerRouteImport } from './routes/regioner'
import { Route as OmOssRouteImport } from './routes/om-oss'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as KategorierRouteImport } from './routes/kategorier'
import { Route as KartaRouteImport } from './routes/karta'
import { Route as GardarRouteImport } from './routes/gardar'
import { Route as BloggNyheterRouteImport } from './routes/blogg-nyheter'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegionerIndexRouteImport } from './routes/regioner.index'
import { Route as KategorierIndexRouteImport } from './routes/kategorier.index'
import { Route as GardarIndexRouteImport } from './routes/gardar.index'
import { Route as BloggNyheterIndexRouteImport } from './routes/blogg-nyheter.index'
import { Route as RegionerSlugRouteImport } from './routes/regioner.$slug'
import { Route as KategorierSlugRouteImport } from './routes/kategorier.$slug'
import { Route as GardarSlugRouteImport } from './routes/gardar.$slug'
import { Route as BloggNyheterSlugRouteImport } from './routes/blogg-nyheter.$slug'

const RegionerRoute = RegionerRouteImport.update({
  id: '/regioner',
  path: '/regioner',
  getParentRoute: () => rootRouteImport,
} as any)
const OmOssRoute = OmOssRouteImport.update({
  id: '/om-oss',
  path: '/om-oss',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const KategorierRoute = KategorierRouteImport.update({
  id: '/kategorier',
  path: '/kategorier',
  getParentRoute: () => rootRouteImport,
} as any)
const KartaRoute = KartaRouteImport.update({
  id: '/karta',
  path: '/karta',
  getParentRoute: () => rootRouteImport,
} as any)
const GardarRoute = GardarRouteImport.update({
  id: '/gardar',
  path: '/gardar',
  getParentRoute: () => rootRouteImport,
} as any)
const BloggNyheterRoute = BloggNyheterRouteImport.update({
  id: '/blogg-nyheter',
  path: '/blogg-nyheter',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionerIndexRoute = RegionerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RegionerRoute,
} as any)
const KategorierIndexRoute = KategorierIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KategorierRoute,
} as any)
const GardarIndexRoute = GardarIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GardarRoute,
} as any)
const BloggNyheterIndexRoute = BloggNyheterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BloggNyheterRoute,
} as any)
const RegionerSlugRoute = RegionerSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => RegionerRoute,
} as any)
const KategorierSlugRoute = KategorierSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => KategorierRoute,
} as any)
const GardarSlugRoute = GardarSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GardarRoute,
} as any)
const BloggNyheterSlugRoute = BloggNyheterSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BloggNyheterRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blogg-nyheter': typeof BloggNyheterRouteWithChildren
  '/gardar': typeof GardarRouteWithChildren
  '/karta': typeof KartaRoute
  '/kategorier': typeof KategorierRouteWithChildren
  '/kontakt': typeof KontaktRoute
  '/om-oss': typeof OmOssRoute
  '/regioner': typeof RegionerRouteWithChildren
  '/blogg-nyheter/$slug': typeof BloggNyheterSlugRoute
  '/gardar/$slug': typeof GardarSlugRoute
  '/kategorier/$slug': typeof KategorierSlugRoute
  '/regioner/$slug': typeof RegionerSlugRoute
  '/blogg-nyheter/': typeof BloggNyheterIndexRoute
  '/gardar/': typeof GardarIndexRoute
  '/kategorier/': typeof KategorierIndexRoute
  '/regioner/': typeof RegionerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/karta': typeof KartaRoute
  '/kontakt': typeof KontaktRoute
  '/om-oss': typeof OmOssRoute
  '/blogg-nyheter/$slug': typeof BloggNyheterSlugRoute
  '/gardar/$slug': typeof GardarSlugRoute
  '/kategorier/$slug': typeof KategorierSlugRoute
  '/regioner/$slug': typeof RegionerSlugRoute
  '/blogg-nyheter': typeof BloggNyheterIndexRoute
  '/gardar': typeof GardarIndexRoute
  '/kategorier': typeof KategorierIndexRoute
  '/regioner': typeof RegionerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blogg-nyheter': typeof BloggNyheterRouteWithChildren
  '/gardar': typeof GardarRouteWithChildren
  '/karta': typeof KartaRoute
  '/kategorier': typeof KategorierRouteWithChildren
  '/kontakt': typeof KontaktRoute
  '/om-oss': typeof OmOssRoute
  '/regioner': typeof RegionerRouteWithChildren
  '/blogg-nyheter/$slug': typeof BloggNyheterSlugRoute
  '/gardar/$slug': typeof GardarSlugRoute
  '/kategorier/$slug': typeof KategorierSlugRoute
  '/regioner/$slug': typeof RegionerSlugRoute
  '/blogg-nyheter/': typeof BloggNyheterIndexRoute
  '/gardar/': typeof GardarIndexRoute
  '/kategorier/': typeof KategorierIndexRoute
  '/regioner/': typeof RegionerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blogg-nyheter'
    | '/gardar'
    | '/karta'
    | '/kategorier'
    | '/kontakt'
    | '/om-oss'
    | '/regioner'
    | '/blogg-nyheter/$slug'
    | '/gardar/$slug'
    | '/kategorier/$slug'
    | '/regioner/$slug'
    | '/blogg-nyheter/'
    | '/gardar/'
    | '/kategorier/'
    | '/regioner/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/karta'
    | '/kontakt'
    | '/om-oss'
    | '/blogg-nyheter/$slug'
    | '/gardar/$slug'
    | '/kategorier/$slug'
    | '/regioner/$slug'
    | '/blogg-nyheter'
    | '/gardar'
    | '/kategorier'
    | '/regioner'
  id:
    | '__root__'
    | '/'
    | '/blogg-nyheter'
    | '/gardar'
    | '/karta'
    | '/kategorier'
    | '/kontakt'
    | '/om-oss'
    | '/regioner'
    | '/blogg-nyheter/$slug'
    | '/gardar/$slug'
    | '/kategorier/$slug'
    | '/regioner/$slug'
    | '/blogg-nyheter/'
    | '/gardar/'
    | '/kategorier/'
    | '/regioner/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BloggNyheterRoute: typeof BloggNyheterRouteWithChildren
  GardarRoute: typeof GardarRouteWithChildren
  KartaRoute: typeof KartaRoute
  KategorierRoute: typeof KategorierRouteWithChildren
  KontaktRoute: typeof KontaktRoute
  OmOssRoute: typeof OmOssRoute
  RegionerRoute: typeof RegionerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/regioner': {
      id: '/regioner'
      path: '/regioner'
      fullPath: '/regioner'
      preLoaderRoute: typeof RegionerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/om-oss': {
      id: '/om-oss'
      path: '/om-oss'
      fullPath: '/om-oss'
      preLoaderRoute: typeof OmOssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kategorier': {
      id: '/kategorier'
      path: '/kategorier'
      fullPath: '/kategorier'
      preLoaderRoute: typeof KategorierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/karta': {
      id: '/karta'
      path: '/karta'
      fullPath: '/karta'
      preLoaderRoute: typeof KartaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gardar': {
      id: '/gardar'
      path: '/gardar'
      fullPath: '/gardar'
      preLoaderRoute: typeof GardarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogg-nyheter': {
      id: '/blogg-nyheter'
      path: '/blogg-nyheter'
      fullPath: '/blogg-nyheter'
      preLoaderRoute: typeof BloggNyheterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regioner/': {
      id: '/regioner/'
      path: '/'
      fullPath: '/regioner/'
      preLoaderRoute: typeof RegionerIndexRouteImport
      parentRoute: typeof RegionerRoute
    }
    '/kategorier/': {
      id: '/kategorier/'
      path: '/'
      fullPath: '/kategorier/'
      preLoaderRoute: typeof KategorierIndexRouteImport
      parentRoute: typeof KategorierRoute
    }
    '/gardar/': {
      id: '/gardar/'
      path: '/'
      fullPath: '/gardar/'
      preLoaderRoute: typeof GardarIndexRouteImport
      parentRoute: typeof GardarRoute
    }
    '/blogg-nyheter/': {
      id: '/blogg-nyheter/'
      path: '/'
      fullPath: '/blogg-nyheter/'
      preLoaderRoute: typeof BloggNyheterIndexRouteImport
      parentRoute: typeof BloggNyheterRoute
    }
    '/regioner/$slug': {
      id: '/regioner/$slug'
      path: '/$slug'
      fullPath: '/regioner/$slug'
      preLoaderRoute: typeof RegionerSlugRouteImport
      parentRoute: typeof RegionerRoute
    }
    '/kategorier/$slug': {
      id: '/kategorier/$slug'
      path: '/$slug'
      fullPath: '/kategorier/$slug'
      preLoaderRoute: typeof KategorierSlugRouteImport
      parentRoute: typeof KategorierRoute
    }
    '/gardar/$slug': {
      id: '/gardar/$slug'
      path: '/$slug'
      fullPath: '/gardar/$slug'
      preLoaderRoute: typeof GardarSlugRouteImport
      parentRoute: typeof GardarRoute
    }
    '/blogg-nyheter/$slug': {
      id: '/blogg-nyheter/$slug'
      path: '/$slug'
      fullPath: '/blogg-nyheter/$slug'
      preLoaderRoute: typeof BloggNyheterSlugRouteImport
      parentRoute: typeof BloggNyheterRoute
    }
  }
}

interface BloggNyheterRouteChildren {
  BloggNyheterSlugRoute: typeof BloggNyheterSlugRoute
  BloggNyheterIndexRoute: typeof BloggNyheterIndexRoute
}

const BloggNyheterRouteChildren: BloggNyheterRouteChildren = {
  BloggNyheterSlugRoute: BloggNyheterSlugRoute,
  BloggNyheterIndexRoute: BloggNyheterIndexRoute,
}

const BloggNyheterRouteWithChildren = BloggNyheterRoute._addFileChildren(
  BloggNyheterRouteChildren,
)

interface GardarRouteChildren {
  GardarSlugRoute: typeof GardarSlugRoute
  GardarIndexRoute: typeof GardarIndexRoute
}

const GardarRouteChildren: GardarRouteChildren = {
  GardarSlugRoute: GardarSlugRoute,
  GardarIndexRoute: GardarIndexRoute,
}

const GardarRouteWithChildren =
  GardarRoute._addFileChildren(GardarRouteChildren)

interface KategorierRouteChildren {
  KategorierSlugRoute: typeof KategorierSlugRoute
  KategorierIndexRoute: typeof KategorierIndexRoute
}

const KategorierRouteChildren: KategorierRouteChildren = {
  KategorierSlugRoute: KategorierSlugRoute,
  KategorierIndexRoute: KategorierIndexRoute,
}

const KategorierRouteWithChildren = KategorierRoute._addFileChildren(
  KategorierRouteChildren,
)

interface RegionerRouteChildren {
  RegionerSlugRoute: typeof RegionerSlugRoute
  RegionerIndexRoute: typeof RegionerIndexRoute
}

const RegionerRouteChildren: RegionerRouteChildren = {
  RegionerSlugRoute: RegionerSlugRoute,
  RegionerIndexRoute: RegionerIndexRoute,
}

const RegionerRouteWithChildren = RegionerRoute._addFileChildren(
  RegionerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BloggNyheterRoute: BloggNyheterRouteWithChildren,
  GardarRoute: GardarRouteWithChildren,
  KartaRoute: KartaRoute,
  KategorierRoute: KategorierRouteWithChildren,
  KontaktRoute: KontaktRoute,
  OmOssRoute: OmOssRoute,
  RegionerRoute: RegionerRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
